_BASE_: "../Base-HOIRCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./output/model_final_280758.pkl"
  META_ARCHITECTURE: "HOIProposalNetwork"
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  CHECKPOINT_PERIOD: 1000
  STEPS: (4000, 5000)
  MAX_ITER: 6000
DATASETS:
  TRAIN: ("vcoco_train", "vcoco_val")
  TEST: ("vcoco_test", )